#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#include "idelay.h"
#include "blueio_board.h"
#include "coredev/iopincfg.h"
#include "iopinctrl.h"

int main(void)
{

	IOPinConfig(0, 30, 0, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL);
//	IOPinSet(0, 30);
	//usDelay(100000);
	//IOPinSet(0, 29);
/*
	while (1)
	{
		IOPinSet(0, 30);
		usDelay(100000);
		IOPinClear(0, 30);
		usDelay(100000);
//		__WFE();
	}*/
	IOPinConfig(0, 25, 0, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL);
	IOPinConfig(0, 24, 0, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL);

	uint32_t val = 0;

	while (1)
	{
		NRF_GPIO->OUTSET = (1 << 25);
		nsDelay(500);
		val = IOPinRead(0, 24);
		NRF_GPIO->OUTCLR = (1 << 25);
		val = IOPinRead(0, 24);
	}

	IOPinConfig(0, BLUEIO_LED_BLUE_PIN, 0, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL);
	IOPinSet(0, BLUEIO_LED_BLUE_PIN);

	// IBK-BLUEIO
	IOPinConfig(BLUEIO_LED_GREEN_PORT, BLUEIO_LED_GREEN_PIN, 0, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL);
	IOPinSet(BLUEIO_LED_GREEN_PORT, BLUEIO_LED_GREEN_PIN);//BLUEIO_LED_GREEN_PIN);
	IOPinConfig(0, BLUEIO_LED_RED_PIN, BLUEIO_LED_RED_PIN, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL);
	IOPinSet(0, BLUEIO_LED_RED_PIN);
  
	// BLUEIO-TAG-BME680
	IOPinConfig(BLUEIO_TAG_BME680_LED2_RED_PORT, BLUEIO_TAG_BME680_LED2_RED_PIN, 0, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL);
	IOPinSet(BLUEIO_TAG_BME680_LED2_RED_PORT, BLUEIO_TAG_BME680_LED2_RED_PIN);
	IOPinConfig(0, BLUEIO_TAG_BME680_LED2_GREEN_PORT, BLUEIO_TAG_BME680_LED2_GREEN_PIN, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL);
	IOPinSet(BLUEIO_TAG_BME680_LED2_GREEN_PORT, BLUEIO_TAG_BME680_LED2_GREEN_PIN);
	IOPinConfig(0, BLUEIO_TAG_BME680_LED2_BLUE_PORT, BLUEIO_TAG_BME680_LED2_BLUE_PIN, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL);
	IOPinSet(BLUEIO_TAG_BME680_LED2_BLUE_PORT, BLUEIO_TAG_BME680_LED2_BLUE_PIN);


	while(true)
	{
/*		IOPinSet(0, BLUEIO_LED_RED_PIN);
		usDelay(1000000);
		IOPinClear(0, BLUEIO_LED_RED_PIN);
		IOPinSet(0, BLUEIO_LED_GREEN_PIN);
		usDelay(1000000);
		IOPinClear(0, BLUEIO_LED_GREEN_PIN);
		IOPinSet(0, BLUEIO_LED_BLUE_PIN);
		usDelay(1000000);
		IOPinClear(0, BLUEIO_LED_BLUE_PIN);*/

		IOPinSet(0, BLUEIO_TAG_BME680_LED2_RED_PIN);
		usDelay(1000000);
		IOPinClear(0, BLUEIO_TAG_BME680_LED2_RED_PIN);
		IOPinSet(0, BLUEIO_TAG_BME680_LED2_GREEN_PIN);
		usDelay(1000000);
		IOPinClear(0, BLUEIO_TAG_BME680_LED2_GREEN_PIN);
		IOPinSet(0, BLUEIO_TAG_BME680_LED2_BLUE_PIN);
		usDelay(1000000);
		IOPinClear(0, BLUEIO_TAG_BME680_LED2_BLUE_PIN);
	}
}
