/*--------------------------------------------------------------------------
File   : ibb_mbedpresso.h

Author : Hoang Nguyen Hoan          May. 25, 2011

Desc   : On board peripheral I/O mapping for IBB-MBEDPRESSO base board.

Copyright (c) 2011, I-SYST, all rights reserved

Permission to use, copy, modify, and distribute this software for any purpose
with or without fee is hereby granted, provided that the above copyright
notice and this permission notice appear in all copies, and none of the
names : I-SYST or its contributors may be used to endorse or
promote products derived from this software without specific prior written
permission.

For info or contributing contact : hnhoan at i-syst dot com

THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

----------------------------------------------------------------------------
Modified by          Date              Description

----------------------------------------------------------------------------*/
#ifndef __IBB_MBEDPRESSO_H__
#define __IBB_MBEDPRESSO_H__

// LED Matrix display
#define MBEDPRESSO_LMX_DATA_PORT	0
#define MBEDPRESSO_LMX_DATA_PIN		22
#define MBEDPRESSO_LMX_WR_PORT		0
#define MBEDPRESSO_LMX_WR_PIN		21
#define MBEDPRESSO_LMX_RD_PORT		1
#define MBEDPRESSO_LMX_RD_PIN		31
#define MBEDPRESSO_LMX_EN_PORT		0
#define MBEDPRESSO_LMX_EN_PIN		3
#define MBEDPRESSO_LMX_CS1_PORT		0
#define MBEDPRESSO_LMX_CS1_PIN		0
#define MBEDPRESSO_LMX_CS2_PORT		0
#define MBEDPRESSO_LMX_CS2_PIN		1
#define MBEDPRESSO_LMX_CS3_PORT		0
#define MBEDPRESSO_LMX_CS3_PIN		2
#define MBEDPRESSO_LMX_CS4_PORT		0
#define MBEDPRESSO_LMX_CS4_PIN		26

// LED
#define MBEDPRESSO_SRPWM_PWM1_PORT		2
#define MBEDPRESSO_SRPWM_PWM1_PIN		4
#define MBEDPRESSO_SRPWM_PWM1_OP		1
#define MBEDPRESSO_SRPWM_PWM2_PORT		2
#define MBEDPRESSO_SRPWM_PWM2_PIN		3
#define MBEDPRESSO_SRPWM_PWM2_OP		1
#define MBEDPRESSO_SRPWM_PWM3_PORT		2
#define MBEDPRESSO_SRPWM_PWM3_PIN		2
#define MBEDPRESSO_SRPWM_PWM3_OP		1

#define MBEDPRESSO_SRPWM_SER_PORT		0
#define MBEDPRESSO_SRPWM_SER_PIN		4
#define MBEDPRESSO_SRPWM_SRCLK_PORT		0
#define MBEDPRESSO_SRPWM_SRCLK_PIN		5
#define MBEDPRESSO_SRPWM_SRCLR_PORT		2
#define MBEDPRESSO_SRPWM_SRCLR_PIN		0
#define MBEDPRESSO_SRPWM_RCLK_PORT		2
#define MBEDPRESSO_SRPWM_RCLK_PIN		1

// Buttons I/O mapping
#define	MBEDPRESSO_BUTTON1_PORT		1
#define	MBEDPRESSO_BUTTON1_PIN		20
#define	MBEDPRESSO_BUTTON2_PORT		1
#define MBEDPRESSO_BUTTON2_PIN		21
#define	MBEDPRESSO_BUTTON3_PORT		1
#define MBEDPRESSO_BUTTON3_PIN		23
#define	MBEDPRESSO_BUTTON4_PORT		1
#define MBEDPRESSO_BUTTON4_PIN		24
#define	MBEDPRESSO_BUTTON5_PORT		1
#define MBEDPRESSO_BUTTON5_PIN		25
#define	MBEDPRESSO_BUTTON6_PORT		1
#define MBEDPRESSO_BUTTON6_PIN		26
#define	MBEDPRESSO_BUTTON7_PORT		1
#define MBEDPRESSO_BUTTON7_PIN		28
#define	MBEDPRESSO_BUTTON8_PORT		1
#define MBEDPRESSO_BUTTON8_PIN		29

// SD card
#define MBEDPRESSO_SD_CMD_PORT		0
#define MBEDPRESSO_SD_CMD_PIN		9
#define MBEDPRESSO_SD_DATA_PORT		0
#define MBEDPRESSO_SD_DATA_PIN		8
#define MBEDPRESSO_SD_CLK_PORT		0
#define MBEDPRESSO_SD_CLK_PIN		7
#define MBEDPRESSO_SD_CS_PORT		0
#define MBEDPRESSO_SD_CS_PIN		6

// Audio UDA1380
#define MBEDPRESSO_UDA1380_I2C_ADDR		(0x30 >> 1)
#define MBEDPRESSO_UDA1380_BCKO_PORT	0
#define MBEDPRESSO_UDA1380_BCKO_PIN		23
#define MBEDPRESSO_UDA1380_WSO_PORT		0
#define MBEDPRESSO_UDA1380_WSO_PIN		24
#define MBEDPRESSO_UDA1380_DATAO_PORT	0
#define MBEDPRESSO_UDA1380_DATAO_PIN	25

#define MBEDPRESSO_UDA1380_SYSCLK_PORT	4
#define MBEDPRESSO_UDA1380_SYSCLK_PIN	29

#define MBEDPRESSO_UDA1380_SDA_PORT		0
#define MBEDPRESSO_UDA1380_SDA_PIN		27
#define MBEDPRESSO_UDA1380_SDA_PIN_MODE		PINSEL_PINMODE_PULLUP
#define MBEDPRESSO_UDA1380_SDA_PIN_ODMODE	PINSEL_PINMODE_OPENDRAIN
#define MBEDPRESSO_UDA1380_SCL_PORT		0
#define MBEDPRESSO_UDA1380_SCL_PIN		28

#define MBEDPRESSO_UDA1380_BCKI_PORT	2
#define MBEDPRESSO_UDA1380_BCKI_PIN		11
#define MBEDPRESSO_UDA1380_WSI_PORT		2
#define MBEDPRESSO_UDA1380_WSI_PIN		12
#define MBEDPRESSO_UDA1380_DATAI_PORT	2
#define MBEDPRESSO_UDA1380_DATAI_PIN	13

// OP Switch
#define MBEDPRESSO_OPSWITCH1_PORT		2
#define MBEDPRESSO_OPSWITCH1_PIN		8
#define MBEDPRESSO_OPSWITCH2_PORT		2
#define MBEDPRESSO_OPSWITCH2_PIN		10

#endif	// __IBB_MBEDPRESSO_H__


