/*--------------------------------------------------------------------------
File   : blueio_board.h

Author : Hoang Nguyen Hoan          Sep. 20, 2014

Desc   : Contains definitions for BlueIO series boards for the IMM-NRF5x 
		 series modules

Copyright (c) 2014, I-SYST inc., all rights reserved

Permission to use, copy, modify, and distribute this software for any purpose
with or without fee is hereby granted, provided that the above copyright
notice and this permission notice appear in all copies, and none of the
names : I-SYST or its contributors may be used to endorse or
promote products derived from this software without specific prior written
permission.

For info or contributing contact : hnhoan at i-syst dot com

THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

----------------------------------------------------------------------------
Modified by          Date              Description

----------------------------------------------------------------------------*/

#ifndef __BLUEIO_BOARD_H__
#define __BLUEIO_BOARD_H__

#ifndef BLUEIO_BOARD
#define BLUEIO_BOARD						1
#endif

// ***** Default pin map for BLUEIO Boards
// LEDs
#define BLUEIO_LED1_PORT					0
#define BLUEIO_LED1_PIN						30
#define BLUEIO_LED1_PINOP					0

#define BLUEIO_LED2_PORT					0
#define BLUEIO_LED2_PIN						29
#define BLUEIO_LED2_PINOP					0

#define BLUEIO_LED3_PORT					0
#define BLUEIO_LED3_PIN						28
#define BLUEIO_LED3_PINOP					0

// Buttons
#define BLUEIO_BUT1_PORT					0
#define BLUEIO_BUT1_PIN						2
#define BLUEIO_BUT1_PINOP					0
#define BLUEIO_BUT2_PORT					0
#define BLUEIO_BUT2_PIN						13
#define BLUEIO_BUT2_PINOP					0

// UART pins
#define BLUEIO_UART_RX_PORT					0
#define BLUEIO_UART_RX_PIN					8
#define BLUEIO_UART_RX_PINOP				0
#define BLUEIO_UART_TX_PORT					0
#define BLUEIO_UART_TX_PIN					7
#define BLUEIO_UART_TX_PINOP				0
#define BLUEIO_UART_CTS_PORT				0
#define BLUEIO_UART_CTS_PIN					12
#define BLUEIO_UART_CTS_PINOP				0
#define BLUEIO_UART_RTS_PORT				0
#define BLUEIO_UART_RTS_PIN					11
#define BLUEIO_UART_RTS_PINOP				0

// I2C0
#define BLUEIO_I2C0_DEVNO					0

#define BLUEIO_I2C0_SCL_PORT				0
#define BLUEIO_I2C0_SCL_PIN					18
#define BLUEIO_I2C0_SCL_PINOP				1
#define BLUEIO_I2C0_SDA_PORT				0
#define BLUEIO_I2C0_SDA_PIN					19
#define BLUEIO_I2C0_SDA_PINOP				1

// SPI1
#define BLUEIO_SPI1_DEVNO					1

#define BLUEIO_SPI1_SCK_PORT				0
#define BLUEIO_SPI1_SCK_PIN					23
#define BLUEIO_SPI1_SCK_PINOP				1
#define BLUEIO_SPI1_MOSI_PORT				0
#define BLUEIO_SPI1_MOSI_PIN				24
#define BLUEIO_SPI1_MOSI_PINOP				1
#define BLUEIO_SPI1_MISO_PORT				0
#define BLUEIO_SPI1_MISO_PIN				25
#define BLUEIO_SPI1_MISO_PINOP				1

// SPI2
#define BLUEIO_SPI2_DEVNO					2

#define BLUEIO_SPI2_SCK_PORT				0
#define BLUEIO_SPI2_SCK_PIN					17
#define BLUEIO_SPI2_SCK_PINOP				1
#define BLUEIO_SPI2_MOSI_PORT				0
#define BLUEIO_SPI2_MOSI_PIN				16
#define BLUEIO_SPI2_MOSI_PINOP				1
#define BLUEIO_SPI2_MISO_PORT				0
#define BLUEIO_SPI2_MISO_PIN				15
#define BLUEIO_SPI2_MISO_PINOP				1

// ***** Most IMM-NRF5x base boards use P0.30 for Bluetooth connection state LED
#define BLUEIO_CONNECT_LED_PORT				BLUEIO_LED1_PORT
#define BLUEIO_CONNECT_LED_PIN				BLUEIO_LED1_PIN

// ***** IBK-BLUEIO - Blue IO breakout board
#define BLUEIO_LED_BLUE_PORT				BLUEIO_LED1_PORT
#define BLUEIO_LED_BLUE_PIN					BLUEIO_LED1_PIN
#define BLUEIO_LED_BLUE_PINOP				BLUEIO_LED1_PINOP
#define BLUEIO_LED_GREEN_PORT				BLUEIO_LED2_PORT
#define BLUEIO_LED_GREEN_PIN				BLUEIO_LED2_PIN
#define BLUEIO_LED_GREEN_PINOP				BLUEIO_LED2_PINOP
#define BLUEIO_LED_RED_PORT					BLUEIO_LED3_PORT
#define BLUEIO_LED_RED_PIN					BLUEIO_LED3_PIN
#define BLUEIO_LED_RED_PINOP				BLUEIO_LED3_PINOP


// ***** BLUEIO-TAG-BME680 board
#define BLUEIO_TAG_BME680_LED1_PORT			BLUEIO_LED1_PORT
#define BLUEIO_TAG_BME680_LED1_PIN			BLUEIO_LED1_PIN
#define BLUEIO_TAG_BME680_LED1_PINOP		BLUEIO_LED1_PINOP

#define BLUEIO_TAG_BME680_LED2_RED_PORT		0
#define BLUEIO_TAG_BME680_LED2_RED_PIN		18
#define BLUEIO_TAG_BME680_LED2_RED_PINOP	0

#define BLUEIO_TAG_BME680_LED2_GREEN_PORT	0
#define BLUEIO_TAG_BME680_LED2_GREEN_PIN	20
#define BLUEIO_TAG_BME680_LED2_GREEN_PINOP	0

#define BLUEIO_TAG_BME680_LED2_BLUE_PORT	0
#define BLUEIO_TAG_BME680_LED2_BLUE_PIN		19
#define BLUEIO_TAG_BME680_LED2_BLUE_PINOP	0

#define BLUEIO_TAG_BME680_I2C_SDA_PORT		0
#define BLUEIO_TAG_BME680_I2C_SDA_PIN		28
#define BLUEIO_TAG_BME680_I2C_SDA_PINOP		1

#define BLUEIO_TAG_BME680_I2C_SCL_PORT		0
#define BLUEIO_TAG_BME680_I2C_SCL_PIN		29
#define BLUEIO_TAG_BME680_I2C_SCL_PINOP		1

#define BLUEIO_TAG_BME680_SPI_SCK_PORT		0
#define BLUEIO_TAG_BME680_SPI_SCK_PIN		17
#define BLUEIO_TAG_BME680_SPI_SCK_PINOP		1

#define BLUEIO_TAG_BME680_SPI_MOSI_PORT		0
#define BLUEIO_TAG_BME680_SPI_MOSI_PIN		16
#define BLUEIO_TAG_BME680_SPI_MOSI_PINOP	1

#define BLUEIO_TAG_BME680_SPI_MISO_PORT		0
#define BLUEIO_TAG_BME680_SPI_MISO_PIN		15
#define BLUEIO_TAG_BME680_SPI_MISO_PINOP	1

#define BLUEIO_TAG_BME680_IMU_CS_PORT		0
#define BLUEIO_TAG_BME680_IMU_CS_PIN		5
#define BLUEIO_TAG_BME680_IMU_CS_PINOP		0

#define BLUEIO_TAG_BME680_IMU_INT_PORT		0
#define BLUEIO_TAG_BME680_IMU_INT_PIN		6
#define BLUEIO_TAG_BME680_IMU_INT_PINOP		0

// ***** BLUEIO-TAG-BME280 board
#define BLUEIO_TAG_BME280_LED1_PORT			BLUEIO_LED1_PORT
#define BLUEIO_TAG_BME280_LED1_PIN			BLUEIO_LED1_PIN
#define BLUEIO_TAG_BME280_LED1_PINOP		BLUEIO_LED1_PINOP

#define BLUEIO_TAG_BME280_LED2_PORT			0
#define BLUEIO_TAG_BME280_LED2_PIN			17
#define BLUEIO_TAG_BME280_LED2_PINOP		0

// BLUEIO-TAG-BMEx80 buttons

#define BLUEIO_TAG_BME280_BUT2_PORT			BLUEIO_BUT2_PORT
#define BLUEIO_TAG_BME280_BUT2_PIN			BLUEIO_BUT2_PIN
#define BLUEIO_TAG_BME280_BUT2_PINOP		BLUEIO_BUT2_PINOP

#define BLUEIO_TAG_BME280_I2C_SDA_PORT		0
#define BLUEIO_TAG_BME280_I2C_SDA_PIN		24
#define BLUEIO_TAG_BME280_I2C_SDA_PINOP		0

#define BLUEIO_TAG_BME280_I2C_SCL_PORT		0
#define BLUEIO_TAG_BME280_I2C_SCL_PIN		25
#define BLUEIO_TAG_BME280_I2C_SCL_PINOP		0

// ***** BLUEIO-TAG-EVIM board

#define BLUEIO_TAG_EVIM_LED2_RED_PORT		BLUEIO_TAG_BME680_LED2_RED_PORT
#define BLUEIO_TAG_EVIM_LED2_RED_PIN		BLUEIO_TAG_BME680_LED2_RED_PIN
#define BLUEIO_TAG_EVIM_LED2_RED_PINOP		BLUEIO_TAG_BME680_LED2_RED_PINOP

#define BLUEIO_TAG_EVIM_LED2_GREEN_PORT		BLUEIO_TAG_BME680_LED2_GREEN_PORT
#define BLUEIO_TAG_EVIM_LED2_GREEN_PIN		BLUEIO_TAG_BME680_LED2_GREEN_PIN
#define BLUEIO_TAG_EVIM_LED2_GREEN_PINOP	BLUEIO_TAG_BME680_LED2_GREEN_PINOP

#define BLUEIO_TAG_EVIM_LED2_BLUE_PORT		BLUEIO_TAG_BME680_LED2_BLUE_PORT
#define BLUEIO_TAG_EVIM_LED2_BLUE_PIN		BLUEIO_TAG_BME680_LED2_BLUE_PIN
#define BLUEIO_TAG_EVIM_LED2_BLUE_PINOP		BLUEIO_TAG_BME680_LED2_BLUE_PINOP

#define BLUEIO_TAG_EVIM_I2C0_DEVNO			0

#define BLUEIO_TAG_EVIM_I2C0_SCL_PORT		0
#define BLUEIO_TAG_EVIM_I2C0_SCL_PIN		29
#define BLUEIO_TAG_EVIM_I2C0_SCL_PINOP		1
#define BLUEIO_TAG_EVIM_I2C0_SDA_PORT		0
#define BLUEIO_TAG_EVIM_I2C0_SDA_PIN		28
#define BLUEIO_TAG_EVIM_I2C0_SDA_PINOP		1

#define BLUEIO_TAG_EVIM_SPI2_SCK_PORT		BLUEIO_SPI2_SCK_PORT
#define BLUEIO_TAG_EVIM_SPI2_SCK_PIN		BLUEIO_SPI2_SCK_PIN
#define BLUEIO_TAG_EVIM_SPI2_SCK_PINOP		BLUEIO_SPI2_SCK_PINOP
#define BLUEIO_TAG_EVIM_SPI2_MOSI_PORT		BLUEIO_SPI2_MOSI_PORT
#define BLUEIO_TAG_EVIM_SPI2_MOSI_PIN		BLUEIO_SPI2_MOSI_PIN
#define BLUEIO_TAG_EVIM_SPI2_MOSI_PINOP		BLUEIO_SPI2_MOSI_PINOP
#define BLUEIO_TAG_EVIM_SPI2_MISO_PORT		BLUEIO_SPI2_MISO_PORT
#define BLUEIO_TAG_EVIM_SPI2_MISO_PIN		BLUEIO_SPI2_MISO_PIN
#define BLUEIO_TAG_EVIM_SPI2_MISO_PINOP		BLUEIO_SPI2_MISO_PINOP

#define BLUEIO_TAG_EVIM_IMU_CS_PORT			0
#define BLUEIO_TAG_EVIM_IMU_CS_PIN			5
#define BLUEIO_TAG_EVIM_IMU_CS_PINOP		0

#define BLUEIO_TAG_EVIM_IMU_INT_PORT		0
#define BLUEIO_TAG_EVIM_IMU_INT_PIN			6
#define BLUEIO_TAG_EVIM_IMU_INT_PINOP		0

#define BLUEIO_TAG_EVIM_EEP_WP_PORT			0
#define BLUEIO_TAG_EVIM_EEP_WP_PIN			27
#define BLUEIO_TAG_EVIM_EEP_WP_PINOP		0

// ***** BLUEIO-ADXL-WCHRG

#define BLUEIO_ADXL_WCHRG_ADXL362_SCK_PORT		BLUEIO_SPI2_SCK_PORT
#define BLUEIO_ADXL_WCHRG_ADXL362_SCK_PIN		BLUEIO_SPI2_SCK_PIN
#define BLUEIO_ADXL_WCHRG_ADXL362_SCK_PINOP		BLUEIO_SPI2_SCK_PINOP
#define BLUEIO_ADXL_WCHRG_ADXL362_MOSI_PORT		BLUEIO_SPI2_MOSI_PORT
#define BLUEIO_ADXL_WCHRG_ADXL362_MOSI_PIN		BLUEIO_SPI2_MOSI_PIN
#define BLUEIO_ADXL_WCHRG_ADXL362_MOSI_PINOP	BLUEIO_SPI2_MOSI_PINOP
#define BLUEIO_ADXL_WCHRG_ADXL362_MISO_PORT		BLUEIO_SPI2_MISO_PORT
#define BLUEIO_ADXL_WCHRG_ADXL362_MISO_PIN		BLUEIO_SPI2_MISO_PIN
#define BLUEIO_ADXL_WCHRG_ADXL362_MISO_PINOP	BLUEIO_SPI2_MISO_PINOP

#define BLUEIO_ADXL_WCHRG_ADXL362_CS_PORT		0
#define BLUEIO_ADXL_WCHRG_ADXL362_CS_PIN		5
#define BLUEIO_ADXL_WCHRG_ADXL362_CS_PPINOP		0

#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PORT		0
#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PIN		6
#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PPINOP	0

#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PORT		0
#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PIN		6
#define BLUEIO_ADXL_WCHRG_ADXL362_INT1_PPINOP	0

#define BLUEIO_ADXL_WCHRG_EEPROM_SCL_PORT		BLUEIO_I2C0_SCL_PORT
#define BLUEIO_ADXL_WCHRG_EEPROM_SCL_PIN		BLUEIO_I2C0_SCL_PIN
#define BLUEIO_ADXL_WCHRG_EEPROM_SCL_PINOP		BLUEIO_I2C0_SCL_PINOP
#define BLUEIO_ADXL_WCHRG_EEPROM_SDA_PORT		BLUEIO_I2C0_SDA_PORT
#define BLUEIO_ADXL_WCHRG_EEPROM_SDA_PIN		BLUEIO_I2C0_SDA_PIN
#define BLUEIO_ADXL_WCHRG_EEPROM_SDA_PINOP		BLUEIO_I2C0_SDA_PINOP

#define BLUEIO_ADXL_WCHRG_EEPROM_WRPROT_PORT	0
#define BLUEIO_ADXL_WCHRG_EEPROM_WRPROT_PIN		20
#define BLUEIO_ADXL_WCHRG_EEPROM_WRPROT_PORT	0

#define BLUEIO_ADXL_WCHRG_FLASH_SCK_PORT		BLUEIO_SPI1_SCK_PORT
#define BLUEIO_ADXL_WCHRG_FLASH_SCK_PIN			BLUEIO_SPI1_SCK_PIN
#define BLUEIO_ADXL_WCHRG_FLASH_SCK_PINOP		BLUEIO_SPI1_SCK_PINOP
#define BLUEIO_ADXL_WCHRG_FLASH_MOSI_PORT		BLUEIO_SPI1_MOSI_PORT
#define BLUEIO_ADXL_WCHRG_FLASH_MOSI_PIN		BLUEIO_SPI1_MOSI_PIN
#define BLUEIO_ADXL_WCHRG_FLASH_MOSI_PINOP		BLUEIO_SPI1_MOSI_PINOP
#define BLUEIO_ADXL_WCHRG_FLASH_MISO_PORT		BLUEIO_SPI1_MISO_PORT
#define BLUEIO_ADXL_WCHRG_FLASH_MISO_PIN		BLUEIO_SPI1_MISO_PIN
#define BLUEIO_ADXL_WCHRG_FLASH_MISO_PINOP		BLUEIO_SPI1_MISO_PINOP

#define BLUEIO_ADXL_WCHRG_FLASH_CS_PORT			0
#define BLUEIO_ADXL_WCHRG_FLASH_CS_PIN			26
#define BLUEIO_ADXL_WCHRG_FLASH_CS_PPINOP		0


#endif // __BLUEIO_BOARD_H__
